"""add_user_role

Revision ID: 3b852344f19c
Revises: 0651ce72084f
Create Date: 2025-12-30 18:59:12.709224

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b852344f19c'
down_revision: Union[str, None] = '0651ce72084f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'PRODUCT_OWNER', 'STAKEHOLDER', name='userrole', native_enum=False), nullable=False, server_default='stakeholder'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
